# -*- coding: utf-8 -*-
"""04_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Rb2CaGSUOtyX67iKhwyXCHfhuVBnQBy
"""

!pip install gradio --quiet

import gradio as gr
import pandas as pd
import xgboost as xgb
import joblib

model = joblib.load("best_xgboost_model.pkl")

def predict(usage_hours, avg_temperature, vibration_level, error_logs_count, pressure_variation, last_maintenance):

    input_data = pd.DataFrame([[usage_hours, avg_temperature, vibration_level, error_logs_count, pressure_variation, last_maintenance]],
                              columns=["usage_hours", "avg_temperature", "vibration_level", "error_logs_count", "pressure_variation", "last_maintenance"])

    prediction = model.predict(input_data)[0]
    return "Expected failure" if prediction == 1 else "No expected failure"

iface = gr.Interface(
    fn=predict,
    inputs=[
        gr.Slider(0, 10000, label="Usage Hours"),
        gr.Slider(0, 100, label="Average Temperature (°C)"),
        gr.Slider(0, 20, label="Vibration Level (m/s^2)"),
        gr.Slider(0, 1000, label="Error Logs Count"),
        gr.Slider(0, 100, label="Pressure Variation (Pa)"),
        gr.Slider(0, 1000, label="Last Maintenance (days ago)")
    ],
    outputs="text",
    title="Predictive Maintenance - XGBoost",
    description="Enter data to predict whether a machine failure will occur."
)

iface.launch()